version: '3.8'

services:
  app:
    container_name: energeticyes_app
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:15.0-alpine'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=energeticyes